# modules/code_generator.py

import pandas as pd

def generate_pipeline_code(original_df, cleaned_df, cleaning_steps):
    """Generate reproducible Python code for cleaning pipeline"""
    
    code = """# Auto-generated Data Cleaning Pipeline
# Generated by DataPrep Assistant

import pandas as pd
import numpy as np

# Load your data
df = pd.read_csv('your_data.csv')

print(f"Original shape: {df.shape}")

# Cleaning Steps
"""
    
    for step in cleaning_steps:
        if step[0] == "duplicates":
            code += "\n# Remove duplicate rows\n"
            code += "df = df.drop_duplicates()\n"
        else:
            col, strategy = step
            code += f"\n# Handle missing values in '{col}'\n"
            
            if "Drop rows" in strategy:
                code += f"df = df.dropna(subset=['{col}'])\n"
            elif "Fill: Mean" in strategy:
                code += f"df['{col}'].fillna(df['{col}'].mean(), inplace=True)\n"
            elif "Fill: Median" in strategy:
                code += f"df['{col}'].fillna(df['{col}'].median(), inplace=True)\n"
            elif "Fill: Mode" in strategy:
                code += f"df['{col}'].fillna(df['{col}'].mode()[0], inplace=True)\n"
            elif "Fill: Forward Fill" in strategy:
                code += f"df['{col}'].fillna(method='ffill', inplace=True)\n"
            elif "Remove" in strategy:
                code += f"""
# Remove outliers from '{col}'
Q1 = df['{col}'].quantile(0.25)
Q3 = df['{col}'].quantile(0.75)
IQR = Q3 - Q1
lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR
df = df[(df['{col}'] >= lower) & (df['{col}'] <= upper)]
"""
            elif "Cap at IQR" in strategy:
                code += f"""
# Cap outliers in '{col}'
Q1 = df['{col}'].quantile(0.25)
Q3 = df['{col}'].quantile(0.75)
IQR = Q3 - Q1
lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR
df['{col}'] = df['{col}'].clip(lower, upper)
"""
    
    code += f"""
print(f"Cleaned shape: {{df.shape}}")

# Save cleaned data
df.to_csv('cleaned_data.csv', index=False)
print("✅ Data cleaning complete!")

# Summary
print(f"Rows removed: {len(original_df) - len(cleaned_df):,}")
print(f"Retention rate: {(len(cleaned_df)/len(original_df)*100):.2f}%")
"""
    
    return code